#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from base import base

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1300132354.978
__CHEETAH_genTimestamp__ = 'Mon Mar 14 15:52:34 2011'
__CHEETAH_src__ = 'view_board.tmpl'
__CHEETAH_srcLastModified__ = 'Mon Mar 14 14:06:30 2011'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class view_board(base):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(view_board, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def title(self, **KWS):



        ## CHEETAH: generated from #def title at line 3, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''View Board: ''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"board.board_name",True) # u'$board.board_name' on line 4, col 13
        if _v is not None: write(_filter(_v, rawExpr=u'$board.board_name')) # from line 4, col 13.
        write(u'''
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def content(self, **KWS):



        ## CHEETAH: generated from #def content at line 7, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''New Thread
<form action="/new_post/" method="post">
\t<input type="hidden" name="board_key" value="''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"board.key",True) # u'$board.key' on line 10, col 47
        if _v is not None: write(_filter(_v, rawExpr=u'$board.key')) # from line 10, col 47.
        write(u'''" />
\t<input type="text" name="message"/>
\t<input type="submit" value="Submit" />
</form>
''')
        for p in VFSL([locals()]+SL+[globals(), builtin],"sorted_posts",True): # generated from line 14, col 1
            write(u'''\t<div class="post" id="''')
            _v = VFSL([locals()]+SL+[globals(), builtin],"p.postnum",True) # u'$p.postnum' on line 15, col 24
            if _v is not None: write(_filter(_v, rawExpr=u'$p.postnum')) # from line 15, col 24.
            write(u'''">
\t\t''')
            _v = VFSL([locals()]+SL+[globals(), builtin],"p.message",True) # u'$p.message' on line 16, col 3
            if _v is not None: write(_filter(_v, rawExpr=u'$p.message')) # from line 16, col 3.
            write(u''' <a href="/view_post/''')
            _v = VFSL([locals()]+SL+[globals(), builtin],"board.key",True) # u'$board.key' on line 16, col 34
            if _v is not None: write(_filter(_v, rawExpr=u'$board.key')) # from line 16, col 34.
            write(u'''/''')
            _v = VFSL([locals()]+SL+[globals(), builtin],"p.postnum",True) # u'$p.postnum' on line 16, col 45
            if _v is not None: write(_filter(_v, rawExpr=u'$p.postnum')) # from line 16, col 45.
            write(u'''"><img class="right" src="/static/images/pencil-24.png" alt="Comment on this thread."></a><br/>
\t\t<div class="reply-preview">
\t\t\t<ul>
''')
            if VFSL([locals()]+SL+[globals(), builtin],"len",False)(p.replies) <= 2: # generated from line 19, col 4
                display_num = VFSL([locals()]+SL+[globals(), builtin],"len",False)(VFSL([locals()]+SL+[globals(), builtin],"p.replies",True))
            else: # generated from line 21, col 4
                display_num = 3
            r = VFN(VFSL([locals()]+SL+[globals(), builtin],"p",True),"replies",True)[-VFSL([locals()]+SL+[globals(), builtin],"display_num",True):]
            write(u'''\t\t\t<span class="reply-info">
''')
            if VFSL([locals()]+SL+[globals(), builtin],"len",False)(VFSL([locals()]+SL+[globals(), builtin],"p.replies",True))>=1: # generated from line 26, col 4
                write(u'''\t\t\t\tLatest ''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"len",False)(VFSL([locals()]+SL+[globals(), builtin],"r",True)) # u'$len($r)' on line 27, col 12
                if _v is not None: write(_filter(_v, rawExpr=u'$len($r)')) # from line 27, col 12.
                write(u'''/''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"len",False)(VFSL([locals()]+SL+[globals(), builtin],"p.replies",True)) # u'$len($p.replies)' on line 27, col 21
                if _v is not None: write(_filter(_v, rawExpr=u'$len($p.replies)')) # from line 27, col 21.
                write(u''' replies:
''')
            else: # generated from line 28, col 4
                write(u'''\t\t\t\tNo replies.
''')
            write(u'''\t\t\t</span>
''')
            for reply in VFSL([locals()]+SL+[globals(), builtin],"r",True): # generated from line 32, col 4
                write(u'''\t\t\t\t<li>
\t\t\t\t\t''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"reply",True)['reply-text'] # u"$reply['reply-text']" on line 34, col 6
                if _v is not None: write(_filter(_v, rawExpr=u"$reply['reply-text']")) # from line 34, col 6.
                write(u'''
\t\t\t\t</li>
''')
            write(u'''\t\t\t</ul>
\t\t</div>

\t</div>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def writeBody(self, **KWS):



        ## CHEETAH: main method generated for this template
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''

''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_view_board= 'writeBody'

## END CLASS DEFINITION

if not hasattr(view_board, '_initCheetahAttributes'):
    templateAPIClass = getattr(view_board, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(view_board)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=view_board()).run()


